name: dbt Feature Watcher

on:
  schedule:
    - cron: '0 13 * * *'  # Runs daily at 8 AM EST
  workflow_dispatch:       # Manual trigger

jobs:
  watch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run Feature Watcher
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          source venv/bin/activate
          python main.py
